const cn = {
    language: "选择语言",
    languageAuto: "自动（设备）",
    greeting: "你好",
    welcome: "欢迎",
    goodbye: "再见",
    about: "关于",
    bePremium: "成为高级用户",
    theme: "深色模式",
    appVersion: "应用版本",
    contactUs: "联系我们",
    comingSoon: "即将推出",
    version: "1.3.2",
    contactEmail: "marolinaana@gmail.com",

    // HomeScreen
    listNamePlaceholder: "列表名称",
    invalidListName: "无效的列表名称",
    errorCreatingList: "创建列表出错",
    errorGeneratingId: "生成列表ID出错",
    close: "关闭",
    createList: "创建列表",
    createListModalTitle: "命名您的清单",
    createListModalSubtitle: "使用清晰的名称，方便之后找到这次购物。",
    listNameExample: "例如：每周采购",
    items: "项目",
    errorDeletingList: "删除列表出错",
    deleteListConfirmTitle: "将列表移至回收站？",
    deleteListConfirmMessage: "要将\"{{0}}\"移至回收站吗？您可以在7天内恢复它。",
    moveToTrash: "移至回收站",
    homeEmptyTitle: "创建第一份清单",
    homeEmptySubtitle: "使用现成模板开始，或创建空清单。",
    homeTemplateSectionTitle: "快速模板",
    homeCreateBlank: "创建空清单",
    homeUseTemplate: "使用模板",
    homeTemplateWeeklyTitle: "每周采购",
    homeTemplateWeeklyDescription: "补充家中日常必需品。",
    homeTemplateBbqTitle: "烧烤",
    homeTemplateBbqDescription: "周末聚餐的快速清单。",
    homeTemplatePharmacyTitle: "药房",
    homeTemplatePharmacyDescription: "需要记住的健康和卫生用品。",
    homeTemplateCleaningTitle: "清洁",
    homeTemplateCleaningDescription: "家庭简单清洁用品。",
    templateItemRice: "米",
    templateItemBeans: "豆类",
    templateItemMilk: "牛奶",
    templateItemBread: "面包",
    templateItemEggs: "鸡蛋",
    templateItemFruit: "水果",
    templateItemMeat: "肉",
    templateItemCharcoal: "木炭",
    templateItemGarlicBread: "蒜蓉面包",
    templateItemSoda: "汽水",
    templateItemIce: "冰",
    templateItemToothpaste: "牙膏",
    templateItemSoap: "肥皂",
    templateItemShampoo: "洗发水",
    templateItemMedicine: "药品",
    templateItemDetergent: "洗涤剂",
    templateItemSponge: "海绵",
    templateItemTrashBags: "垃圾袋",
    templateItemDisinfectant: "消毒剂",

    // ListScreen
    backToLists: "返回列表",
    validNameRequired: "项目需要有效的名称。",
    invalidPrice: "无效价格",
    invalidPriceMessage: "请输入有效价格。",
    invalidQuantity: "无效数量",
    invalidQuantityMessage: "请输入有效数量。",
    itemPlaceholder: "项目",
    pricePlaceholder: "价格",
    quantityPlaceholder: "数量",
    totalChecked: "已选总计",
    totalUnchecked: "未选总计",
    totalPrice: "总价格",
    emptyListMessage: "您的列表为空。",
    listEmptyTitle: "从一个商品开始",
    listEmptySubtitle: "点按建议，或使用下方字段创建您的清单。",
    quickAddSuggestions: "快速建议",
    addSuggestedItem: "添加建议商品",

    // DeleteScreen
    deletedLists: "已删除列表",
    listsInTrash: "个列表在回收站",
    listInTrash: "个列表在回收站",
    clearTrash: "清空回收站",
    clearAll: "全部清除",
    clearTrashConfirm: "清空回收站",
    clearTrashMessage: "您确定要永久删除回收站中的所有列表吗？",
    cancel: "取消",
    deletedOn: "删除于",
    restore: "恢复",
    delete: "删除",
    deleteForever: "永久删除",
    deleteForeverMessage: "您确定要永久删除\"{{0}}\"吗？此操作无法撤销。",
    emptyTrash: "回收站为空",
    emptyTrashMessage: "目前没有已删除的列表",

    // ConfigScreen
    emailNotAvailable: "邮箱不可用",
    contactEmailMessage: "请联系我们：{{0}}",

    // Sorting options
    sortBy: "排序方式",
    sortByAddition: "添加顺序",
    sortByAlphabetical: "字母顺序",
    sortByStatus: "按状态（已选在底部）",
    close: "关闭",

    // Share
    shareList: "分享",
    shareError: "分享错误",
    shareErrorMessage: "无法分享列表"
};

export default cn;
