
const en = {
    language: "Select Language",
    languageAuto: "Auto (Device)",
    greeting: "Hello",
    welcome: "Welcome",
    goodbye: "Goodbye",
    about: "About",
    bePremium: "Be Premium",
    theme: "Dark Mode",
    appVersion: "App Version",
    contactUs: "Contact Us",
    comingSoon: "Coming Soon",
    version: "1.4.3",
    contactEmail: "marolinaana@gmail.com",
    tabTrash: "Trash",
    tabLists: "Lists",
    tabSettings: "Settings",

    // HomeScreen
    listNamePlaceholder: "List Name",
    invalidListName: "Invalid list name",
    errorCreatingList: "Error creating list",
    errorGeneratingId: "Error generating list ID",
    close: "Close",
    createList: "Create List",
    createListModalTitle: "Name your list",
    createListModalSubtitle: "Use a clear name so you can find this shopping trip later.",
    listNameExample: "Example: Weekly groceries",
    items: "items",
    errorDeletingList: "Error deleting list",
    deleteListConfirmTitle: "Move list to trash?",
    deleteListConfirmMessage: "Do you want to move \"{{0}}\" to the trash? You can restore it for 7 days.",
    moveToTrash: "Move to Trash",
    homeEmptyTitle: "Create your first list",
    homeEmptySubtitle: "Start from a ready-made template or create an empty list.",
    homeTemplateSectionTitle: "Quick templates",
    homeCreateBlank: "Create empty list",
    homeUseTemplate: "Use template",
    homeTemplateWeeklyTitle: "Weekly groceries",
    homeTemplateWeeklyDescription: "Everyday essentials to restock your home.",
    homeTemplateBbqTitle: "Barbecue",
    homeTemplateBbqDescription: "A quick starter list for a weekend cookout.",
    homeTemplatePharmacyTitle: "Pharmacy",
    homeTemplatePharmacyDescription: "Health and hygiene basics to remember.",
    homeTemplateCleaningTitle: "Cleaning",
    homeTemplateCleaningDescription: "Supplies for a simple home cleanup.",
    templateItemRice: "Rice",
    templateItemBeans: "Beans",
    templateItemMilk: "Milk",
    templateItemBread: "Bread",
    templateItemEggs: "Eggs",
    templateItemFruit: "Fruit",
    templateItemMeat: "Meat",
    templateItemCharcoal: "Charcoal",
    templateItemGarlicBread: "Garlic bread",
    templateItemSoda: "Soda",
    templateItemIce: "Ice",
    templateItemToothpaste: "Toothpaste",
    templateItemSoap: "Soap",
    templateItemShampoo: "Shampoo",
    templateItemMedicine: "Medicine",
    templateItemDetergent: "Detergent",
    templateItemSponge: "Sponge",
    templateItemTrashBags: "Trash bags",
    templateItemDisinfectant: "Disinfectant",

    // ListScreen
    backToLists: "Back to lists",
    loading: "Loading...",
    validNameRequired: "The item needs a valid name.",
    invalidPrice: "Invalid price",
    invalidPriceMessage: "Please enter a valid price.",
    invalidQuantity: "Invalid quantity",
    invalidQuantityMessage: "Please enter a valid quantity.",
    itemPlaceholder: "Item",
    pricePlaceholder: "price",
    quantityPlaceholder: "n",
    totalChecked: "Total checked",
    totalUnchecked: "Total unchecked",
    totalPrice: "Total price",
    emptyListMessage: "Your list is empty.",
    listEmptyTitle: "Start with one item",
    listEmptySubtitle: "Tap a suggestion or use the fields below to build your list.",
    quickAddSuggestions: "Quick suggestions",
    addSuggestedItem: "Add suggested item",
    frequentItemSuggestionsTitle: "Items you often use",
    frequentItemSuggestionsSubtitle: "Based only on lists saved on this device.",
    addFrequentItem: "Add frequent item",

    checkedItemAccessibilityLabel: "{{0}} checked",
    uncheckedItemAccessibilityLabel: "{{0}} not checked",
    deleteItemAccessibilityLabel: "Delete {{0}}",
    addItemAccessibilityLabel: "Add item",

    // DeleteScreen
    deletedLists: "Deleted Lists",
    listsInTrash: "lists in trash",
    listInTrash: "list in trash",
    clearTrash: "Clear Trash",
    clearAll: "Clear All",
    clearTrashConfirm: "Clear Trash",
    clearTrashMessage: "Do you really want to permanently delete all lists from the trash?",
    cancel: "Cancel",
    deletedOn: "Deleted on",
    restore: "Restore",
    delete: "Delete",
    deleteForever: "Delete Permanently",
    deleteForeverMessage: "Do you really want to permanently delete \"{{0}}\"? This action cannot be undone.",
    emptyTrash: "Empty Trash",
    emptyTrashMessage: "There are no deleted lists at the moment",

    // ConfigScreen
    emailNotAvailable: "Email not available",
    contactEmailMessage: "Please contact us at: {{0}}",

    // Sorting options
    sortBy: "Sort by",
    sortByAddition: "Order of addition",
    sortByAlphabetical: "Alphabetical order",
    sortByStatus: "By status (checked at bottom)",
    close: "Close",

    // Share
    shareList: "Share",
    shareError: "Share error",
    shareErrorMessage: "Unable to share the list"
};

export default en;
