const es = {
    language: "Seleccionar Idioma",
    languageAuto: "Automático (Dispositivo)",
    greeting: "Hola",
    welcome: "Bienvenido",
    goodbye: "Adiós",
    about: "Acerca de",
    bePremium: "Ser Premium",
    theme: "Modo Oscuro",
    appVersion: "Versión de la App",
    contactUs: "Contáctanos",
    comingSoon: "Próximamente",
    version: "1.4.3",
    contactEmail: "marolinaana@gmail.com",
    tabTrash: "Papelera",
    tabLists: "Listas",
    tabSettings: "Ajustes",

    // HomeScreen
    listNamePlaceholder: "Nombre de la Lista",
    invalidListName: "Nombre de lista inválido",
    errorCreatingList: "Error al crear lista",
    errorGeneratingId: "Error al generar ID de lista",
    close: "Cerrar",
    createList: "Crear Lista",
    createListModalTitle: "Nombre su lista",
    createListModalSubtitle: "Use un nombre claro para encontrar esta compra después.",
    listNameExample: "Ejemplo: Compra semanal",
    items: "artículos",
    errorDeletingList: "Error al eliminar lista",
    deleteListConfirmTitle: "¿Mover lista a la papelera?",
    deleteListConfirmMessage: "¿Desea mover \"{{0}}\" a la papelera? Puede restaurarla durante 7 días.",
    moveToTrash: "Mover a la papelera",
    homeEmptyTitle: "Crea tu primera lista",
    homeEmptySubtitle: "Comienza con una plantilla lista o crea una lista vacía.",
    homeTemplateSectionTitle: "Plantillas rápidas",
    homeCreateBlank: "Crear lista vacía",
    homeUseTemplate: "Usar plantilla",
    homeTemplateWeeklyTitle: "Compra semanal",
    homeTemplateWeeklyDescription: "Esenciales para reponer la casa.",
    homeTemplateBbqTitle: "Barbacoa",
    homeTemplateBbqDescription: "Una lista rápida para el fin de semana.",
    homeTemplatePharmacyTitle: "Farmacia",
    homeTemplatePharmacyDescription: "Básicos de salud e higiene para recordar.",
    homeTemplateCleaningTitle: "Limpieza",
    homeTemplateCleaningDescription: "Productos para una limpieza simple en casa.",
    templateItemRice: "Arroz",
    templateItemBeans: "Frijoles",
    templateItemMilk: "Leche",
    templateItemBread: "Pan",
    templateItemEggs: "Huevos",
    templateItemFruit: "Fruta",
    templateItemMeat: "Carne",
    templateItemCharcoal: "Carbón",
    templateItemGarlicBread: "Pan de ajo",
    templateItemSoda: "Refresco",
    templateItemIce: "Hielo",
    templateItemToothpaste: "Pasta dental",
    templateItemSoap: "Jabón",
    templateItemShampoo: "Champú",
    templateItemMedicine: "Medicina",
    templateItemDetergent: "Detergente",
    templateItemSponge: "Esponja",
    templateItemTrashBags: "Bolsas de basura",
    templateItemDisinfectant: "Desinfectante",

    // ListScreen
    backToLists: "Volver a listas",
    loading: "Cargando...",
    validNameRequired: "El artículo necesita un nombre válido.",
    invalidPrice: "Precio inválido",
    invalidPriceMessage: "Por favor, ingrese un precio válido.",
    invalidQuantity: "Cantidad inválida",
    invalidQuantityMessage: "Por favor, ingrese una cantidad válida.",
    itemPlaceholder: "Artículo",
    pricePlaceholder: "precio",
    quantityPlaceholder: "cant",
    totalChecked: "Total marcados",
    totalUnchecked: "Total desmarcados",
    totalPrice: "Precio total",
    emptyListMessage: "Su lista está vacía.",
    listEmptyTitle: "Empiece con un artículo",
    listEmptySubtitle: "Toque una sugerencia o use los campos de abajo para crear su lista.",
    quickAddSuggestions: "Sugerencias rápidas",
    addSuggestedItem: "Agregar artículo sugerido",
    frequentItemSuggestionsTitle: "Artículos que usa a menudo",
    frequentItemSuggestionsSubtitle: "Basado solo en listas guardadas en este dispositivo.",
    addFrequentItem: "Agregar artículo frecuente",

    checkedItemAccessibilityLabel: "{{0}} marcado",
    uncheckedItemAccessibilityLabel: "{{0}} sin marcar",
    deleteItemAccessibilityLabel: "Eliminar {{0}}",
    addItemAccessibilityLabel: "Agregar artículo",

    // DeleteScreen
    deletedLists: "Listas Eliminadas",
    listsInTrash: "listas en papelera",
    listInTrash: "lista en papelera",
    clearTrash: "Vaciar Papelera",
    clearAll: "Limpiar Todo",
    clearTrashConfirm: "Vaciar Papelera",
    clearTrashMessage: "¿Realmente desea eliminar permanentemente todas las listas de la papelera?",
    cancel: "Cancelar",
    deletedOn: "Eliminada el",
    restore: "Restaurar",
    delete: "Eliminar",
    deleteForever: "Eliminar Permanentemente",
    deleteForeverMessage: "¿Realmente desea eliminar \"{{0}}\" permanentemente? Esta acción no se puede deshacer.",
    emptyTrash: "Papelera Vacía",
    emptyTrashMessage: "No hay listas eliminadas en este momento",

    // ConfigScreen
    emailNotAvailable: "Email no disponible",
    contactEmailMessage: "Por favor contáctenos en: {{0}}",

    // Sorting options
    sortBy: "Ordenar por",
    sortByAddition: "Orden de adición",
    sortByAlphabetical: "Orden alfabético",
    sortByStatus: "Por estado (marcados abajo)",
    close: "Cerrar",

    // Share
    shareList: "Compartir",
    shareError: "Error al compartir",
    shareErrorMessage: "No se pudo compartir la lista"
};

export default es;
