const fr = {
    language: "Sélectionner la Langue",
    languageAuto: "Automatique (Appareil)",
    greeting: "Bonjour",
    welcome: "Bienvenue",
    goodbye: "Au revoir",
    about: "À propos",
    bePremium: "Devenir Premium",
    theme: "Mode Sombre",
    appVersion: "Version de l'App",
    contactUs: "Nous Contacter",
    comingSoon: "Bientôt Disponible",
    version: "1.3.2",
    contactEmail: "marolinaana@gmail.com",
    tabTrash: "Corbeille",
    tabLists: "Listes",
    tabSettings: "Réglages",

    // HomeScreen
    listNamePlaceholder: "Nom de la Liste",
    invalidListName: "Nom de liste invalide",
    errorCreatingList: "Erreur lors de la création de la liste",
    errorGeneratingId: "Erreur lors de la génération de l'ID de liste",
    close: "Fermer",
    createList: "Créer une Liste",
    createListModalTitle: "Nommez votre liste",
    createListModalSubtitle: "Utilisez un nom clair pour retrouver ces courses plus tard.",
    listNameExample: "Exemple : courses de la semaine",
    items: "articles",
    errorDeletingList: "Erreur lors de la suppression de la liste",
    deleteListConfirmTitle: "Déplacer la liste vers la corbeille ?",
    deleteListConfirmMessage: "Voulez-vous déplacer \"{{0}}\" vers la corbeille ? Vous pouvez la restaurer pendant 7 jours.",
    moveToTrash: "Déplacer vers la corbeille",
    homeEmptyTitle: "Créez votre première liste",
    homeEmptySubtitle: "Commencez avec un modèle prêt ou créez une liste vide.",
    homeTemplateSectionTitle: "Modèles rapides",
    homeCreateBlank: "Créer une liste vide",
    homeUseTemplate: "Utiliser le modèle",
    homeTemplateWeeklyTitle: "Courses de la semaine",
    homeTemplateWeeklyDescription: "Les essentiels pour remplir la maison.",
    homeTemplateBbqTitle: "Barbecue",
    homeTemplateBbqDescription: "Une liste rapide pour le week-end.",
    homeTemplatePharmacyTitle: "Pharmacie",
    homeTemplatePharmacyDescription: "Bases santé et hygiène à ne pas oublier.",
    homeTemplateCleaningTitle: "Ménage",
    homeTemplateCleaningDescription: "Produits pour un nettoyage simple.",
    templateItemRice: "Riz",
    templateItemBeans: "Haricots",
    templateItemMilk: "Lait",
    templateItemBread: "Pain",
    templateItemEggs: "Oeufs",
    templateItemFruit: "Fruits",
    templateItemMeat: "Viande",
    templateItemCharcoal: "Charbon",
    templateItemGarlicBread: "Pain à l'ail",
    templateItemSoda: "Soda",
    templateItemIce: "Glace",
    templateItemToothpaste: "Dentifrice",
    templateItemSoap: "Savon",
    templateItemShampoo: "Shampooing",
    templateItemMedicine: "Médicament",
    templateItemDetergent: "Détergent",
    templateItemSponge: "Éponge",
    templateItemTrashBags: "Sacs poubelle",
    templateItemDisinfectant: "Désinfectant",

    // ListScreen
    backToLists: "Retour aux listes",
    loading: "Chargement...",
    validNameRequired: "L'article a besoin d'un nom valide.",
    invalidPrice: "Prix invalide",
    invalidPriceMessage: "Veuillez saisir un prix valide.",
    invalidQuantity: "Quantité invalide",
    invalidQuantityMessage: "Veuillez saisir une quantité valide.",
    itemPlaceholder: "Article",
    pricePlaceholder: "prix",
    quantityPlaceholder: "qté",
    totalChecked: "Total coché",
    totalUnchecked: "Total non coché",
    totalPrice: "Prix total",
    emptyListMessage: "Votre liste est vide.",
    listEmptyTitle: "Commencez avec un article",
    listEmptySubtitle: "Touchez une suggestion ou utilisez les champs ci-dessous pour créer votre liste.",
    quickAddSuggestions: "Suggestions rapides",
    addSuggestedItem: "Ajouter l'article suggéré",
    frequentItemSuggestionsTitle: "Articles que vous utilisez souvent",
    frequentItemSuggestionsSubtitle: "Basé uniquement sur les listes enregistrées sur cet appareil.",
    addFrequentItem: "Ajouter un article fréquent",

    checkedItemAccessibilityLabel: "{{0}} coché",
    uncheckedItemAccessibilityLabel: "{{0}} non coché",
    deleteItemAccessibilityLabel: "Supprimer {{0}}",
    addItemAccessibilityLabel: "Ajouter un article",

    // DeleteScreen
    deletedLists: "Listes Supprimées",
    listsInTrash: "listes dans la corbeille",
    listInTrash: "liste dans la corbeille",
    clearTrash: "Vider la Corbeille",
    clearAll: "Tout Effacer",
    clearTrashConfirm: "Vider la Corbeille",
    clearTrashMessage: "Voulez-vous vraiment supprimer définitivement toutes les listes de la corbeille?",
    cancel: "Annuler",
    deletedOn: "Supprimée le",
    restore: "Restaurer",
    delete: "Supprimer",
    deleteForever: "Supprimer Définitivement",
    deleteForeverMessage: "Voulez-vous vraiment supprimer \"{{0}}\" définitivement? Cette action ne peut pas être annulée.",
    emptyTrash: "Corbeille Vide",
    emptyTrashMessage: "Il n'y a aucune liste supprimée pour le moment",

    // ConfigScreen
    emailNotAvailable: "Email non disponible",
    contactEmailMessage: "Veuillez nous contacter à: {{0}}",

    // Sorting options
    sortBy: "Trier par",
    sortByAddition: "Ordre d'ajout",
    sortByAlphabetical: "Ordre alphabétique",
    sortByStatus: "Par statut (cochés en bas)",
    close: "Fermer",

    // Share
    shareList: "Partager",
    shareError: "Erreur de partage",
    shareErrorMessage: "Impossible de partager la liste"
};

export default fr;
