const pt = {
    language: "Selecionar Idioma",
    languageAuto: "Automático (Dispositivo)",
    greeting: "Olá",
    welcome: "Bem-vindo",
    goodbye: "Adeus",
    about: "Sobre",
    bePremium: "Seja Premium",
    theme: "Modo Escuro",
    appVersion: "Versão do App",
    contactUs: "Fale Conosco",
    comingSoon: "Em Breve",
    version: "1.3.2",
    contactEmail: "marolinaana@gmail.com",

    // HomeScreen
    listNamePlaceholder: "Nome da Lista",
    invalidListName: "Nome da lista inválido",
    errorCreatingList: "Erro ao criar lista",
    errorGeneratingId: "Erro ao gerar ID da lista",
    close: "Fechar",
    createList: "Criar Lista",
    createListModalTitle: "Nomeie sua lista",
    createListModalSubtitle: "Use um nome claro para encontrar esta compra depois.",
    listNameExample: "Exemplo: Compra da semana",
    items: "itens",
    errorDeletingList: "Erro ao deletar lista",
    deleteListConfirmTitle: "Mover lista para a lixeira?",
    deleteListConfirmMessage: "Deseja mover \"{{0}}\" para a lixeira? Você pode restaurá-la por 7 dias.",
    moveToTrash: "Mover para a lixeira",
    homeEmptyTitle: "Crie sua primeira lista",
    homeEmptySubtitle: "Comece com um modelo pronto ou crie uma lista vazia.",
    homeTemplateSectionTitle: "Modelos rápidos",
    homeCreateBlank: "Criar lista vazia",
    homeUseTemplate: "Usar modelo",
    homeTemplateWeeklyTitle: "Compra da semana",
    homeTemplateWeeklyDescription: "Itens essenciais para abastecer a casa.",
    homeTemplateBbqTitle: "Churrasco",
    homeTemplateBbqDescription: "Uma lista rápida para o fim de semana.",
    homeTemplatePharmacyTitle: "Farmácia",
    homeTemplatePharmacyDescription: "Básicos de saúde e higiene para lembrar.",
    homeTemplateCleaningTitle: "Faxina",
    homeTemplateCleaningDescription: "Produtos para uma limpeza simples em casa.",
    templateItemRice: "Arroz",
    templateItemBeans: "Feijão",
    templateItemMilk: "Leite",
    templateItemBread: "Pão",
    templateItemEggs: "Ovos",
    templateItemFruit: "Frutas",
    templateItemMeat: "Carne",
    templateItemCharcoal: "Carvão",
    templateItemGarlicBread: "Pão de alho",
    templateItemSoda: "Refrigerante",
    templateItemIce: "Gelo",
    templateItemToothpaste: "Creme dental",
    templateItemSoap: "Sabonete",
    templateItemShampoo: "Shampoo",
    templateItemMedicine: "Remédio",
    templateItemDetergent: "Detergente",
    templateItemSponge: "Esponja",
    templateItemTrashBags: "Sacos de lixo",
    templateItemDisinfectant: "Desinfetante",

    // ListScreen
    backToLists: "Voltar para listas",
    validNameRequired: "O item precisa de um nome válido.",
    invalidPrice: "Preço inválido",
    invalidPriceMessage: "Por favor, insira um preço válido.",
    invalidQuantity: "Quantidade inválida",
    invalidQuantityMessage: "Por favor, insira uma quantidade válida.",
    itemPlaceholder: "Item",
    pricePlaceholder: "preço",
    quantityPlaceholder: "qtd",
    totalChecked: "Total marcados",
    totalUnchecked: "Total desmarcados",
    totalPrice: "Preço total",
    emptyListMessage: "Sua lista está vazia.",
    listEmptyTitle: "Comece com um item",
    listEmptySubtitle: "Toque em uma sugestão ou use os campos abaixo para montar sua lista.",
    quickAddSuggestions: "Sugestões rápidas",
    addSuggestedItem: "Adicionar item sugerido",

    // DeleteScreen
    deletedLists: "Listas Deletadas",
    listsInTrash: "listas na lixeira",
    listInTrash: "lista na lixeira",
    clearTrash: "Limpar Lixeira",
    clearAll: "Limpar Tudo",
    clearTrashConfirm: "Limpar Lixeira",
    clearTrashMessage: "Você realmente deseja deletar permanentemente todas as listas da lixeira?",
    cancel: "Cancelar",
    deletedOn: "Deletada em",
    restore: "Restaurar",
    delete: "Deletar",
    deleteForever: "Deletar Permanentemente",
    deleteForeverMessage: "Você realmente deseja deletar \"{{0}}\" permanentemente? Esta ação não pode ser desfeita.",
    emptyTrash: "Lixeira Vazia",
    emptyTrashMessage: "Não há listas deletadas no momento",

    // ConfigScreen
    emailNotAvailable: "Email não disponível",
    contactEmailMessage: "Entre em contato conosco em: {{0}}",

    // Sorting options
    sortBy: "Ordenar por",
    sortByAddition: "Ordem de adição",
    sortByAlphabetical: "Ordem alfabética",
    sortByStatus: "Por status (marcados embaixo)",
    close: "Fechar",

    // Share
    shareList: "Compartilhar",
    shareError: "Erro ao compartilhar",
    shareErrorMessage: "Não foi possível compartilhar a lista"
};

export default pt;
